const genreMap = {
    '1': 'Action',
    '2': 'Adventure',
    '3': 'Racing',
    '4': 'Comedy',
    '5': 'Avant Garde',
    '6': 'Mythology',
    '7': 'Mystery',
    '8': 'Drama',
    '10': 'Fantasy',
    '11': 'Strategy Game',
    '13': 'Historical',
    '14': 'Horror',
    '17': 'Martial Arts',
    '18': 'Mecha',
    '19': 'Music',
    '20': 'Parody',
    '21': 'Samurai',
    '22': 'Romance',
    '23': 'School',
    '24': 'Sci-Fi',
    '26': 'Girls Love',
    '28': 'Boys Love',
    '29': 'Space',
    '30': 'Sports',
    '31': 'Super Power',
    '32': 'Vampire',
    '35': 'Harem',
    '36': 'Slice of Life',
    '37': 'Supernatural',
    '38': 'Military',
    '39': 'Detective',
    '40': 'Psychological',
    '41': 'Suspense',
    '46': 'Award Winning',
    '47': 'Gourmet',
    '50': 'Adult Cast',
    '51': 'Anthropomorphic',
    '52': 'CGDCT',
    '53': 'Childcare',
    '54': 'Combat Sports',
    '55': 'Delinquents',
    '56': 'Educational',
    '57': 'Gag Humor',
    '58': 'Gore',
    '59': 'High Stakes Game',
    '60': 'Idols (Female)',
    '61': 'Idols (Male)',
    '62': 'Isekai',
    '63': 'Iyashikei',
    '64': 'Love Polygon',
    '66': 'Mahou Shoujo',
    '67': 'Medical',
    '68': 'Organized Crime',
    '69': 'Otaku Culture',
    '70': 'Performing Arts',
    '71': 'Pets',
    '72': 'Reincarnation',
    '73': 'Reverse Harem',
    '74': 'Love Status Quo',
    '75': 'Showbiz',
    '76': 'Survival',
    '77': 'Team Sports',
    '78': 'Time Travel',
    '79': 'Video Game',
    '81': 'Crossdressing',
  };
export default genreMap;