import { CSSProperties } from 'react';

const AuthStyles: { [key: string]: CSSProperties } = {
  button: {
    width: '100%',
    maxWidth: '400px',
    padding: '15px',
    backgroundColor: '#4a90e2',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    cursor: 'pointer',
    marginBottom: '15px',
    fontWeight: 'bold',
  },
  container: {
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#260d6e',
    fontFamily: "'Arial', sans-serif",
    padding: '20px',
    color: 'white',
  },
  errorText: {
    marginTop: '15px',
    color: '#ff6b6b',
    fontWeight: 500,
    fontSize: '14px',
    textAlign: 'center',
    maxWidth: '400px',
  },
  footer: {
    fontFamily: '"Niramit", sans-serif',
    fontSize: '12px',
    fontStyle: 'italic',
    fontWeight: 'bold',
    marginBottom: '40px',
    color: 'white',
  },
  forgotPassword: {
    fontSize: '14px',
    color: 'rgba(255, 255, 255, 0.8)',
    textDecoration: 'none',
    marginBottom: '30px',
    cursor: 'pointer',
    textAlign: 'center',
  },
  input: {
    width: '100%',
    maxWidth: '400px',
    padding: '15px',
    marginBottom: '15px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '16px',
    boxSizing: 'border-box',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  logo: {
    fontFamily: '"Niramit", sans-serif',
    fontSize: '80px',
    fontStyle: 'italic',
    marginBottom: '20px',
    color: 'white',
  },
  passwordHint: {
    fontSize: '12px',
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'left',
    width: '100%',
    maxWidth: '400px',
    marginBottom: '20px',
  },
  secondaryButton: {
    width: '100%',
    maxWidth: '400px',
    padding: '15px',
    backgroundColor: 'transparent',
    color: 'white',
    border: '1px solid white',
    borderRadius: '8px',
    fontSize: '16px',
    cursor: 'pointer',
    fontWeight: 'bold',
    marginBottom: '30px',
  },
  subtitle: {
    fontFamily: '"Niramit", sans-serif',
    fontSize: '32px',
    fontStyle: 'italic',
    fontWeight: 'bold',
    marginBottom: '40px',
    color: 'white',
  },
};

export default AuthStyles;