import { CSSProperties } from 'react';

const HomeStyles: { [key: string]: CSSProperties } = {
  animeDescription: {
    fontSize: '14px',
    color: '#808080',
    margin: '0 0 15px 0',
    lineHeight: '1.5',
  },
  animeList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  animeInfoContainer: {
    maxWidth: '900px',
    margin: '0 auto',
    backgroundColor: '#1e1e1e',
    borderRadius: '10px',
    padding: '30px',
    boxShadow: '0 4px 8px rgba(0,0,0,0.3)'
  },
  animeInfoHeader: {
    fontSize: '2rem',
    margin: '0 0 10px 0',
    color: '#ffffff',
    paddingBottom: '10px'
  },
  animeInfoSubheader: {
    color: '#aaa',
    fontStyle: 'italic',
    marginBottom: '20px'
  },
  animeInfoButton: {
    backgroundColor: 'transparent',
    color: '#397d6e',
    border: '1px solid #260d6e',
    padding: '10px 20px',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '8px'
  },
  animeInfoButtonContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: '20px'
  },
  animeInfoDescription: {
    color: '#bbb',
    lineHeight: '1.6'
  },
  animeInfoDetailsContainer: {
    backgroundColor: '#2a2a2a',
    borderRadius: '5px',
    padding: '15px',
  },
  animeInfoDetailsTitle: {
    fontSize: '1.2rem',
    color: '#ffffff',
    marginBottom: '15px'
  },
  animeInfoDetailsText: {
    margin: '5px 0',
    color: '#bbb'
  },
  animeInfoDivider: {
    borderTop: '1px solid #333',
    margin: '20px 0'
  },
  animeInfoImage: {
    width: '250px',
    height: '350px',
    objectFit: 'contain',
    borderRadius: '5px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.5)'
  },
  animeInfoTrailerContainer: {
    marginTop: '30px'
  },
  animeItem: {
    backgroundColor: '#1e1e1e',
    borderRadius: '8px',
    padding: '20px',
    marginBottom: '15px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  animeTitle: {
    fontSize: '28px',
    margin: '0 0 10px 0',
    color: '#ffffff',
  },
  container: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    fontFamily: "'Arial', sans-serif",
    paddingTop: '70px',
  },
  content: {
    padding: '20px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  divider: {
    border: 'none',
    height: '1px',
    backgroundColor: '#ddd',
    margin: '20px 0',
  },
  favouriteButton: {
    backgroundColor: '#2f2f2f',
    border: '1px solid #949494',
    color: '#ffffff',
    padding: '5px 10px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  filterActionButtons: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  filterApplyButton: {
    padding: '12px',
    borderRadius: '5px',
    border: 'none',
    backgroundColor: '#260d6e',
    color: '#fff',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: 'bold',
  },
  filterClearButton: {
    padding: '12px',
    borderRadius: '5px',
    border: 'none',
    backgroundColor: '#ff6b6b',
    color: '#fff',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: 'bold',
  },
  filterCloseButton: {
    padding: '12px',
    borderRadius: '5px',
    border: '1px solid #ccc',
    backgroundColor: '#f5f5f5',
    color: '#333',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: 'bold',
  },
  filterGroup: {
    marginBottom: '15px',
  },
  filterInput: {
    width: '100%',
    padding: '10px',
    borderRadius: '5px',
    border: '1px solid #ddd',
    fontSize: '14px',
  },
  filterLabel: {
    display: 'block',
    marginBottom: '8px',
    fontWeight: 'bold',
    color: '#444',
  },
  filterSelect: {
    width: '100%',
    padding: '10px',
    borderRadius: '5px',
    border: '1px solid #ddd',
    fontSize: '14px',
  },
  filtersContainer: {
    marginBottom: '20px',
  },
  filtersPanel: {
    position: 'fixed',
    top: '70px',
    right: '0',
    width: '400px',
    backgroundColor: '#fff',
    boxShadow: '-2px 0 10px rgba(0,0,0,0.2)',
    zIndex: 999,
    height: 'calc(100vh - 70px)',
    overflowY: 'auto',
  },
  filtersPanelContent: {
    padding: '20px',
  },
  filtersPanelTitle: {
    color: '#260d6e',
    fontSize: '22px',
    marginBottom: '20px',
    borderBottom: '2px solid #260d6e',
    paddingBottom: '10px',
  },
  genreButton: {
    padding: '10px',
    borderRadius: '5px',
    border: '1px solid #ccc',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'background-color 0.3s ease, color 0.3s ease',
    textAlign: 'center',
  },
  genresContainer: {
    marginBottom: '20px',
  },
  genresControlButton: {
    padding: '8px 15px',
    borderRadius: '5px',
    border: '1px solid #ccc',
    backgroundColor: '#6200ea',
    color: '#fff',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'background-color 0.3s ease',
  },
  genresControlButtons: {
    display: 'flex',
    gap: '10px',
    justifyContent: 'center',
    marginTop: '10px',
  },
  genresGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '10px',
    marginBottom: '15px',
  },
  genreTag: {
    backgroundColor: '#0f4e09',
    border: '1px solid #b4afb9',
    color: '#ffffff',
    padding: '5px 12px',
    borderRadius: '5px',
    fontSize: '0.9rem'
  },
  header: {
    backgroundColor: '#260d6e',
    padding: '5px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: 'white',
    boxShadow: '0 2px 5px rgba(0,0,0,0.2)',
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    height: '70px',
  },
  headerFilterButton: {
    backgroundColor: '#8e44ad',
    color: 'white',
    border: 'none',
    borderRadius: '20px',
    padding: '8px 15px',
    cursor: 'pointer',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontWeight: 'bold',
  },
  headerSearchButton: {
    backgroundColor: '#8e44ad',
    color: 'white',
    border: 'none',
    borderRadius: '20px',
    padding: '8px 15px',
    cursor: 'pointer',
    height: '36px',
    fontWeight: 'bold',
  },
  headerSearchContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flex: 1,
    maxWidth: '600px',
  },
  headerSearchInput: {
    flex: 1,
    padding: '8px 15px',
    borderRadius: '20px',
    border: 'none',
    fontSize: '14px',
    height: '36px',
  },
  logo: {
    fontFamily: '"Niramit", sans-serif',
    fontSize: '36px',
    fontStyle: 'italic',
    color: 'white',
    margin: 0,
  },
  modalContent: {
    backgroundColor: '#1e1e1e',
    padding: '20px',
    borderRadius: '8px',
    maxWidth: '600px',
    width: '90%',
    maxHeight: '80vh',
    overflowY: 'auto',
    boxShadow: '0 4px 8px rgba(0,0,0,0.3)',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1001,
  },
  navButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: 'white',
    cursor: 'pointer',
    fontSize: '20px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  navContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
  },
  optionButton:{
    border: '1px solid #949494',
    color: '#ffffff',
    borderRadius: '4px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 20px',
    backgroundColor: '#65558f',
    fontSize: '14px',
    transition: 'background-color 0.3s ease, color 0.3s ease',              
  },
  searchButton: {
    backgroundColor: '#260d6e',
    color: 'white',
    border: 'none',
    borderRadius: '20px',
    padding: '10px 20px',
    cursor: 'pointer',
  },
  searchContainer: {
    display: 'flex',
    margin: '20px 0',
    gap: '10px',
  },
  searchInput: {
    flex: 1,
    padding: '10px 15px',
    borderRadius: '20px',
    border: '1px solid #ddd',
    fontSize: '14px',
  },
  sectionSubtitle: {
    fontFamily: '"Niramit", sans-serif',
    fontSize: '16px',
    fontStyle: 'italic',
    marginBottom: '40px',
    color: 'gray',
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: '54px',
    fontStyle: 'italic',
    margin: '50px 0 30px 0',
    color: '#260d6e',
    textAlign: 'center',
  },
};

export default HomeStyles;