import { CSSProperties } from 'react';

const HomeStyles: { [key: string]: CSSProperties } = {
  animeDescription: {
    fontSize: '14px',
    color: '#808080',
    margin: '0 0 15px 0',
    lineHeight: '1.5',
  },
  animeItem: {
    backgroundColor: '#1e1e1e',
    borderRadius: '8px',
    padding: '20px',
    marginBottom: '15px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  animeList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  animeTitle: {
    fontSize: '28px',
    margin: '0 0 10px 0',
    color: '#ffffff',
  },
  container: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    fontFamily: "'Arial', sans-serif",
    paddingTop: '70px',
  },
  content: {
    padding: '20px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  divider: {
    border: 'none',
    height: '1px',
    backgroundColor: '#ddd',
    margin: '20px 0',
  },
  favouriteButton: {
    backgroundColor: '#2f2f2f',
    border: '1px solid #949494',
    color: '#ffffff',
    padding: '5px 10px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  header: {
    backgroundColor: '#260d6e',
    padding: '5px 10px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: 'white',
    boxShadow: '0 2px 5px rgba(0,0,0,0.2)',
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  logo: {
    fontFamily: '"Niramit", sans-serif',
    fontSize: '48px',
    fontStyle: 'italic',
    color: 'white',
  },
  navContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
  },
  navButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: 'white',
    cursor: 'pointer',
    fontSize: '20px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  searchButton: {
    backgroundColor: '#260d6e',
    color: 'white',
    border: 'none',
    borderRadius: '20px',
    padding: '10px 20px',
    cursor: 'pointer',
  },
  searchContainer: {
    display: 'flex',
    margin: '20px 0',
    gap: '10px',
  },
  searchInput: {
    flex: 1,
    padding: '10px 15px',
    borderRadius: '20px',
    border: '1px solid #ddd',
    fontSize: '14px',
  },
  sectionTitle: {
    fontSize: '54px',
    fontStyle: 'italic',
    margin: '50px 0 30px 0',
    color: '#260d6e',
    textAlign: 'center',
  },
  sectionSubtitle: {
    fontFamily: '"Niramit", sans-serif',
    fontSize: '16px',
    fontStyle: 'italic',
    marginBottom: '40px',
    color: 'gray',
    textAlign: 'center',
  },
};

export default HomeStyles;